# Site settings
title: Vijay Dhakar
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: @Dhakad9
user_description: I'm a cyberSecurity, techEnthusiast , knownDeveloper, blogger, gamer, youtuber.
user_title: Software Developer
email: vijaysarkar887@gmail.com
twitter_username: @VijayDhakar9
github_username:  @Dhakad9
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
